// Generated by CoffeeScript 1.7.1
(function() {
  var LIMIT_TIME, setColor, start, step, stop, toggle, zeroPadding;

  LIMIT_TIME = 100 * 1000;

  $(function() {
    $(".fit-text").fitText();
    return $(document).on("click touchstart", function() {
      return toggle();
    });
  });

  toggle = function() {
    if (this.timer) {
      return stop();
    } else {
      return start();
    }
  };

  start = function() {
    this.startTime = new Date();
    this.timer = setInterval((function() {
      return step();
    }), 50);
    return setColor("yellow");
  };

  stop = function() {
    clearTimeout(this.timer);
    this.timer = null;
    $("#second").text("00");
    $("#ms").text("000");
    setColor("lime");
    return $(document.body).removeClass("blinking");
  };

  step = function() {
    var ms, second, time;
    time = LIMIT_TIME - (new Date() - this.startTime);
    if (time < 0) {
      stop();
      return;
    }
    if (time < 20 * 1000) {
      setColor("red");
    }
    if (time < 10 * 1000) {
      $(document.body).addClass("blinking");
    }
    second = Math.floor(time / 1000);
    ms = zeroPadding(time % 1000);
    $("#second").text(second);
    return $("#ms").text(ms);
  };

  zeroPadding = function(num) {
    return ("00" + num).slice(-3);
  };

  setColor = function(color) {
    $(document.body).css("color", color);
    return $(".color-border").css("border-color", color);
  };

}).call(this);
